export { default as ModuleView } from './ModuleView.vue'
export { default as ClassView } from './ClassView.vue'
export { default as TraitView } from './TraitView.vue'
export { default as DocumentSidebar } from './DocumentSidebar.vue'
export { default as DocumentTopbar } from './DocumentTopbar.vue'