[workspace]
resolver = "2"
members = ["projects/*"]
default-members = [
    "projects/skadi-backend",
]
exclude = [
    "projects/skadi-frontend",
    "projects/.DS_Store",
]

[workspace.dependencies]

[profile.release]
lto = true
panic = "abort"
