// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Contact information for the exposed API.
 * @export
 * @interface Contact
 */
export interface Contact {
    [key: string]: object | any;

    /**
     * The email address of the contact person/organization. This MUST be in the format of an email address.
     * @type {string}
     * @memberof Contact
     */
    email?: string | null;
    /**
     * The identifying name of the contact person/organization.
     * @type {string}
     * @memberof Contact
     */
    name?: string | null;
    /**
     * The URL pointing to the contact information. This MUST be in the format of a URL.
     * @type {string}
     * @memberof Contact
     */
    url?: string | null;
}


