// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ClassInfo } from './class-info';
import { ModuleInfo } from './module-info';
import { ModuleItem } from './module-item';
import { TraitInfo } from './trait-info';

/**
 * @type DocumentInfo
 * @export
 */
export type DocumentInfo = ClassInfo | ModuleInfo | TraitInfo;



