// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DocumentInfoOneOf1
 */
export interface DocumentInfoOneOf1 {
    /**
     * 
     * @type {string}
     * @memberof DocumentInfoOneOf1
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentInfoOneOf1
     */
    type: DocumentInfoOneOf1TypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum DocumentInfoOneOf1TypeEnum {
    Class = 'Class'
}



