// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DocumentInfoOneOf } from './document-info-one-of';
import { DocumentInfoOneOf1 } from './document-info-one-of1';
import { DocumentInfoOneOf2 } from './document-info-one-of2';
import { ModuleItem } from './module-item';

/**
 * @type DocumentInfo
 * @export
 */
export type DocumentInfo = DocumentInfoOneOf | DocumentInfoOneOf1 | DocumentInfoOneOf2;



