// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ModuleItem } from './module-item';

/**
 * 
 * @export
 * @interface DocumentInfoOneOf
 */
export interface DocumentInfoOneOf {
    /**
     * 
     * @type {string}
     * @memberof DocumentInfoOneOf
     */
    documentation: string;
    /**
     * 
     * @type {Array<ModuleItem>}
     * @memberof DocumentInfoOneOf
     */
    items: Array<ModuleItem>;
    /**
     * 
     * @type {string}
     * @memberof DocumentInfoOneOf
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentInfoOneOf
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof DocumentInfoOneOf
     */
    type: DocumentInfoOneOfTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum DocumentInfoOneOfTypeEnum {
    Module = 'module'
}



