// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';
import { QueryStyle } from './query-style';
import { ReferenceOrForHeader } from './reference-or-for-header';

/**
 * A single encoding definition applied to a single schema property.
 * @export
 * @interface Encoding
 */
export interface Encoding {
    [key: string]: object | any;

    /**
     * Determines whether the parameter value SHOULD allow reserved characters, as defined by RFC3986 :/?#[]@!$&\'()*+,;= to be included without percent-encoding. The default value is false. This property SHALL be ignored if the request body media type is not application/x-www-form-urlencoded or multipart/form-data. If a value is explicitly defined, then the value of `contentType` (implicit or explicit) SHALL be ignored.
     * @type {boolean}
     * @memberof Encoding
     */
    allowReserved?: boolean;
    /**
     * The Content-Type for encoding a specific property. Default value depends on the property type: for object - application/json; for array – the default is defined based on the inner type. for all other cases the default is `application/octet-stream`. The value can be a specific media type (e.g. application/json), a wildcard media type (e.g. image/_*), or a comma-separated list of the two types.
     * @type {string}
     * @memberof Encoding
     */
    contentType?: string | null;
    /**
     * When this is true, property values of type array or object generate separate parameters for each value of the array, or key-value-pair of the map. For other types of properties this property has no effect. When style is form, the default value is true. For all other styles, the default value is false. This property SHALL be ignored if the request body media type is not application/x-www-form-urlencoded or multipart/form-data. If a value is explicitly defined, then the value of `contentType` (implicit or explicit) SHALL be ignored.  In this Library this value defaults to false always despite the specification.
     * @type {boolean}
     * @memberof Encoding
     */
    explode?: boolean;
    /**
     * A map allowing additional information to be provided as headers, for example Content-Disposition. Content-Type is described separately and SHALL be ignored in this section. This property SHALL be ignored if the request body media type is not a multipart.
     * @type {{ [key: string]: ReferenceOrForHeader; }}
     * @memberof Encoding
     */
    headers?: { [key: string]: ReferenceOrForHeader; };
    /**
     * Describes how a specific property value will be serialized depending on its type. See Parameter Object for details on the style property. The behavior follows the same values as query parameters, including default values. This property SHALL be ignored if the request body media type is not application/x-www-form-urlencoded  or multipart/form-data. If a value is explicitly defined, then the value of `contentType` (implicit or explicit) SHALL be ignored.
     * @type {QueryStyle | Null}
     * @memberof Encoding
     */
    style?: QueryStyle | Null;
}


