// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Example
 */
export interface Example {
    [key: string]: object | any;

    /**
     * Long description for the example. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof Example
     */
    description?: string | null;
    /**
     * A URI that points to the literal example. This provides the capability to reference examples that cannot easily be included in JSON or YAML documents. The `value` field and `externalValue` field are mutually exclusive. See the rules for resolving Relative References.
     * @type {string}
     * @memberof Example
     */
    externalValue?: string | null;
    /**
     * Short description for the example.
     * @type {string}
     * @memberof Example
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof Example
     */
    value?: string;
}


