// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Allows referencing an external resource for extended documentation.
 * @export
 * @interface ExternalDocumentation
 */
export interface ExternalDocumentation {
    [key: string]: object | any;

    /**
     * A description of the target documentation. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof ExternalDocumentation
     */
    description?: string | null;
    /**
     * REQUIRED. The URL for the target documentation. This MUST be in the format of a URL.
     * @type {string}
     * @memberof ExternalDocumentation
     */
    url: string;
}


