// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AnyType } from './any-type';
import { HeaderOneOf } from './header-one-of';
import { HeaderOneOf1 } from './header-one-of1';
import { MediaType } from './media-type';
import { Model154945945 } from './model154945945';
import { Model154945960 } from './model154945960';
import { SchemaObject } from './schema-object';

/**
 * @type Header
 * The Header Object follows the structure of the Parameter Object with the following changes:  1) name MUST NOT be specified, it is given in the corresponding headers map. 2) in MUST NOT be specified, it is implicitly in header. 3) All traits that are affected by the location MUST be applicable to a location of header (for example, style).
 * @export
 */
export type Header = HeaderOneOf | HeaderOneOf1;



