// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MediaType } from './media-type';

/**
 * A map containing the representations for the parameter. The key is the media type and the value describes it. The map MUST only contain one entry.
 * @export
 * @interface HeaderOneOf1
 */
export interface HeaderOneOf1 {
    /**
     * 
     * @type {{ [key: string]: MediaType; }}
     * @memberof HeaderOneOf1
     */
    content: { [key: string]: MediaType; };
}


