// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { SchemaObject } from './schema-object';

/**
 * The schema defining the type used for the parameter.
 * @export
 * @interface HeaderOneOf
 */
export interface HeaderOneOf {
    /**
     * 
     * @type {SchemaObject}
     * @memberof HeaderOneOf
     */
    schema: SchemaObject;
}


