// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface HomeStatistics
 */
export interface HomeStatistics {
    /**
     * 
     * @type {number}
     * @memberof HomeStatistics
     */
    all_downloads: number;
    /**
     * 
     * @type {number}
     * @memberof HomeStatistics
     */
    all_packages: number;
    /**
     * 
     * @type {number}
     * @memberof HomeStatistics
     */
    all_users: number;
}


