// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The possible types of values in JSON Schema documents.  See [JSON Schema 4.2.1. Instance Data Model](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-4.2.1).
 * @export
 * @enum {string}
 */
export enum InstanceType {
    Null = 'null',
    Boolean = 'boolean',
    Object = 'object',
    Array = 'array',
    Number = 'number',
    String = 'string',
    Integer = 'integer'
}



