// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Encoding } from './encoding';
import { Null } from './null';
import { ReferenceOrForExample } from './reference-or-for-example';
import { SchemaObject } from './schema-object';

/**
 * 
 * @export
 * @interface MediaType
 */
export interface MediaType {
    [key: string]: object | any;

    /**
     * 
     * @type {{ [key: string]: Encoding; }}
     * @memberof MediaType
     */
    encoding?: { [key: string]: Encoding; };
    /**
     * 
     * @type {object}
     * @memberof MediaType
     */
    example?: object;
    /**
     * 
     * @type {{ [key: string]: ReferenceOrForExample; }}
     * @memberof MediaType
     */
    examples?: { [key: string]: ReferenceOrForExample; };
    /**
     * 
     * @type {SchemaObject | Null}
     * @memberof MediaType
     */
    schema?: SchemaObject | Null;
}


