// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OAuth2FlowsOneOf3AuthorizationCode } from './oauth2-flows-one-of3-authorization-code';

/**
 * 
 * @export
 * @interface OAuth2FlowsOneOf3
 */
export interface OAuth2FlowsOneOf3 {
    /**
     * 
     * @type {OAuth2FlowsOneOf3AuthorizationCode}
     * @memberof OAuth2FlowsOneOf3
     */
    authorizationCode: OAuth2FlowsOneOf3AuthorizationCode;
}


