// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OAuth2FlowsOneOf1Password } from './oauth2-flows-one-of1-password';

/**
 * 
 * @export
 * @interface OAuth2FlowsOneOf2
 */
export interface OAuth2FlowsOneOf2 {
    /**
     * 
     * @type {OAuth2FlowsOneOf1Password}
     * @memberof OAuth2FlowsOneOf2
     */
    clientCredentials: OAuth2FlowsOneOf1Password;
}


