// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface OAuth2FlowsOneOfImplicit
 */
export interface OAuth2FlowsOneOfImplicit {
    /**
     * 
     * @type {string}
     * @memberof OAuth2FlowsOneOfImplicit
     */
    authorizationUrl: string;
    /**
     * 
     * @type {string}
     * @memberof OAuth2FlowsOneOfImplicit
     */
    refreshUrl?: string | null;
    /**
     * 
     * @type {{ [key: string]: string; }}
     * @memberof OAuth2FlowsOneOfImplicit
     */
    scopes?: { [key: string]: string; };
}


