// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OAuth2FlowsOneOf } from './oauth2-flows-one-of';
import { OAuth2FlowsOneOf1 } from './oauth2-flows-one-of1';
import { OAuth2FlowsOneOf1Password } from './oauth2-flows-one-of1-password';
import { OAuth2FlowsOneOf2 } from './oauth2-flows-one-of2';
import { OAuth2FlowsOneOf3 } from './oauth2-flows-one-of3';
import { OAuth2FlowsOneOf3AuthorizationCode } from './oauth2-flows-one-of3-authorization-code';
import { OAuth2FlowsOneOfImplicit } from './oauth2-flows-one-of-implicit';

/**
 * @type OAuth2Flows
 * @export
 */
export type OAuth2Flows = OAuth2FlowsOneOf | OAuth2FlowsOneOf1 | OAuth2FlowsOneOf2 | OAuth2FlowsOneOf3;



