// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { OAuth2FlowsOneOfImplicit } from './oauth2-flows-one-of-implicit';

/**
 * 
 * @export
 * @interface OAuth2FlowsOneOf
 */
export interface OAuth2FlowsOneOf {
    /**
     * 
     * @type {OAuth2FlowsOneOfImplicit}
     * @memberof OAuth2FlowsOneOf
     */
    implicit: OAuth2FlowsOneOfImplicit;
}


