// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Components } from './components';
import { ExternalDocumentation } from './external-documentation';
import { Info } from './info';
import { Null } from './null';
import { ReferenceOrForPathItem } from './reference-or-for-path-item';
import { Server } from './server';
import { Tag } from './tag';

/**
 * 
 * @export
 * @interface OpenApi
 */
export interface OpenApi {
    [key: string]: object | any;

    /**
     * An element to hold various schemas for the document.
     * @type {Components | Null}
     * @memberof OpenApi
     */
    components?: Components | Null;
    /**
     * Additional external documentation.
     * @type {ExternalDocumentation | Null}
     * @memberof OpenApi
     */
    externalDocs?: ExternalDocumentation | Null;
    /**
     * 
     * @type {Info}
     * @memberof OpenApi
     */
    info: Info;
    /**
     * The default value for the `$schema` keyword within Schema Objects contained within this OAS document. This MUST be in the form of a URI.
     * @type {string}
     * @memberof OpenApi
     */
    jsonSchemaDialect?: string | null;
    /**
     * 
     * @type {string}
     * @memberof OpenApi
     */
    openapi: string;
    /**
     * The available paths and operations for the API.
     * @type {any | Null}
     * @memberof OpenApi
     */
    paths?: any | Null;
    /**
     * A declaration of which security mechanisms can be used across the API. The list of values includes alternative security requirement objects that can be used. Only one of the security requirement objects need to be satisfied to authorize a request. Individual operations can override this definition. Global security settings may be overridden on a per-path basis.
     * @type {Array<{ [key: string]: Array<string>; }>}
     * @memberof OpenApi
     */
    security?: Array<{ [key: string]: Array<string>; }>;
    /**
     * An array of Server Objects, which provide connectivity information to a target server. If the servers property is not provided, or is an empty array, the default value would be a Server Object with a url value of /.
     * @type {Array<Server>}
     * @memberof OpenApi
     */
    servers?: Array<Server>;
    /**
     * A list of tags used by the document with additional metadata. The order of the tags can be used to reflect on their order by the parsing tools. Not all tags that are used by the Operation Object must be declared. The tags that are not declared MAY be organized randomly or based on the tool\'s logic. Each tag name in the list MUST be unique.
     * @type {Array<Tag>}
     * @memberof OpenApi
     */
    tags?: Array<Tag>;
    /**
     * The incoming webhooks that MAY be received as part of this API and that the API consumer MAY choose to implement. Closely related to the `callbacks` feature, this section describes requests initiated other than by an API call, for example by an out of band registration. The key name is a unique string to refer to each webhook, while the (optionally referenced) Path Item Object describes a request that may be initiated by the API provider and the expected responses.
     * @type {{ [key: string]: ReferenceOrForPathItem; }}
     * @memberof OpenApi
     */
    webhooks?: { [key: string]: ReferenceOrForPathItem; };
}


