// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ExternalDocumentation } from './external-documentation';
import { Null } from './null';
import { ReferenceOrForMapOfReferenceOrForPathItem } from './reference-or-for-map-of-reference-or-for-path-item';
import { ReferenceOrForParameter } from './reference-or-for-parameter';
import { ReferenceOrForRequestBody } from './reference-or-for-request-body';
import { Responses } from './responses';
import { Server } from './server';

/**
 * Describes a single API operation on a path.
 * @export
 * @interface Operation
 */
export interface Operation {
    [key: string]: object | any;

    /**
     * Callbacks for the operation.
     * @type {{ [key: string]: ReferenceOrForMapOfReferenceOrForPathItem; }}
     * @memberof Operation
     */
    callbacks?: { [key: string]: ReferenceOrForMapOfReferenceOrForPathItem; };
    /**
     * Declares this operation to be deprecated.Default value is false.
     * @type {boolean}
     * @memberof Operation
     */
    deprecated?: boolean;
    /**
     * A verbose explanation of the operation behavior. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof Operation
     */
    description?: string | null;
    /**
     * Additional external documentation for this operation.
     * @type {ExternalDocumentation | Null}
     * @memberof Operation
     */
    externalDocs?: ExternalDocumentation | Null;
    /**
     * Unique string used to identify the operation. The id MUST be unique among all operations described in the API. Tools and libraries MAY use the operationId to uniquely identify an operation, therefore, it is RECOMMENDED to follow common programming naming conventions.
     * @type {string}
     * @memberof Operation
     */
    operationId?: string | null;
    /**
     * A list of parameters that are applicable for this operation. If a parameter is already defined at the Path Item, the new definition will override it but can never remove it. The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location. The list can use the Reference Object to link to parameters that are defined at the OpenAPI Object\'s components/parameters.
     * @type {Array<ReferenceOrForParameter>}
     * @memberof Operation
     */
    parameters?: Array<ReferenceOrForParameter>;
    /**
     * The request body applicable for this operation. The requestBody is fully supported in HTTP methods where the HTTP 1.1 specification RFC7231 has explicitly defined semantics for request bodies. In other cases where the HTTP spec is vague (such as [GET](https://tools.ietf.org/html/rfc7231#section-4.3.1), [HEAD](https://tools.ietf.org/html/rfc7231#section-4.3.2) and [DELETE](https://tools.ietf.org/html/rfc7231#section-4.3.5)), requestBody is permitted but does not have well-defined semantics and SHOULD be avoided if possible.
     * @type {ReferenceOrForRequestBody | Null}
     * @memberof Operation
     */
    requestBody?: ReferenceOrForRequestBody | Null;
    /**
     * The list of possible responses as they are returned from executing this operation.
     * @type {Responses | Null}
     * @memberof Operation
     */
    responses?: Responses | Null;
    /**
     * A declaration of which security mechanisms can be used for this operation. The list of values includes alternative security requirement objects that can be used. Only one of the security requirement objects need to be satisfied to authorize a request. This definition overrides any declared top-level security. To remove a top-level security declaration, an empty array can be used.
     * @type {Array<{ [key: string]: Array<string>; }>}
     * @memberof Operation
     */
    security?: Array<{ [key: string]: Array<string>; }>;
    /**
     * An alternative server array to service this operation. If an alternative server object is specified at the Path Item Object or Root level, it will be overridden by this value.
     * @type {Array<Server>}
     * @memberof Operation
     */
    servers?: Array<Server>;
    /**
     * A short summary of what the operation does.
     * @type {string}
     * @memberof Operation
     */
    summary?: string | null;
    /**
     * A list of tags for API documentation control. Tags can be used for logical grouping of operations by resources or any other qualifier.
     * @type {Array<string>}
     * @memberof Operation
     */
    tags?: Array<string>;
}


