// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PackageDetail
 */
export interface PackageDetail {
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    documentation: string;
    /**
     * 
     * @type {number}
     * @memberof PackageDetail
     */
    downloads: number;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    license: string;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    organization: string;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    package_id: string;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    repository: string;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    summary: string;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    update_time: string;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    update_user: string;
    /**
     * 
     * @type {string}
     * @memberof PackageDetail
     */
    version: string;
}


