// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PackageInfo
 */
export interface PackageInfo {
    /**
     * 
     * @type {string}
     * @memberof PackageInfo
     */
    author: string;
    /**
     * 
     * @type {string}
     * @memberof PackageInfo
     */
    description: string;
    /**
     * 
     * @type {number}
     * @memberof PackageInfo
     */
    downloads: number;
    /**
     * 
     * @type {string}
     * @memberof PackageInfo
     */
    last_update: string;
    /**
     * 
     * @type {string}
     * @memberof PackageInfo
     */
    license: string;
    /**
     * 
     * @type {string}
     * @memberof PackageInfo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof PackageInfo
     */
    organization: string;
    /**
     * 
     * @type {string}
     * @memberof PackageInfo
     */
    repository: string;
    /**
     * 
     * @type {string}
     * @memberof PackageInfo
     */
    version: string;
}


