// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PackageVersion
 */
export interface PackageVersion {
    /**
     * 
     * @type {string}
     * @memberof PackageVersion
     */
    update_time: string;
    /**
     * 
     * @type {string}
     * @memberof PackageVersion
     */
    update_user: string;
    /**
     * 
     * @type {string}
     * @memberof PackageVersion
     */
    version: string;
}


