// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { AnyType } from './any-type';
import { Model154945940 } from './model154945940';
import { Model154945960 } from './model154945960';
import { ParameterOneOf } from './parameter-one-of';
import { ParameterOneOf1 } from './parameter-one-of1';
import { ParameterOneOf2 } from './parameter-one-of2';
import { ParameterOneOf3 } from './parameter-one-of3';

/**
 * @type Parameter
 * @export
 */
export type Parameter = ParameterOneOf | ParameterOneOf1 | ParameterOneOf2 | ParameterOneOf3;



