// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';
import { Operation } from './operation';
import { ReferenceOrForParameter } from './reference-or-for-parameter';
import { Server } from './server';

/**
 * Describes the operations available on a single path. A Path Item MAY be empty, due to ACL constraints. The path itself is still exposed to the documentation viewer but they will not know which operations and parameters are available.
 * @export
 * @interface PathItem
 */
export interface PathItem {
    [key: string]: object | any;

    /**
     * Allows for a referenced definition of this path item. The referenced structure MUST be in the form of a Path Item Object.  In case a Path Item Object field appears both in the defined object and the referenced object, the behavior is undefined. See the rules for resolving Relative References.
     * @type {string}
     * @memberof PathItem
     */
    $ref?: string | null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof PathItem
     */
    _delete?: Operation | Null;
    /**
     * An optional, string description, intended to apply to all operations in this path. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof PathItem
     */
    description?: string | null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof PathItem
     */
    get?: Operation | Null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof PathItem
     */
    head?: Operation | Null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof PathItem
     */
    options?: Operation | Null;
    /**
     * A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there. The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location. The list can use the Reference Object to link to parameters that are defined at the OpenAPI Object\'s components/parameters.
     * @type {Array<ReferenceOrForParameter>}
     * @memberof PathItem
     */
    parameters?: Array<ReferenceOrForParameter>;
    /**
     * 
     * @type {Operation | Null}
     * @memberof PathItem
     */
    patch?: Operation | Null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof PathItem
     */
    post?: Operation | Null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof PathItem
     */
    put?: Operation | Null;
    /**
     * An alternative server array to service all operations in this path.
     * @type {Array<Server>}
     * @memberof PathItem
     */
    servers?: Array<Server>;
    /**
     * An optional, string summary, intended to apply to all operations in this path.
     * @type {string}
     * @memberof PathItem
     */
    summary?: string | null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof PathItem
     */
    trace?: Operation | Null;
}


