// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Link } from './link';
import { ReferenceOrForExampleAnyOf } from './reference-or-for-example-any-of';

/**
 * 
 * @export
 * @interface ReferenceOrForLink
 */
export interface ReferenceOrForLink {
    /**
     * REQUIRED. The reference identifier. This MUST be in the form of a URI.
     * @type {string}
     * @memberof ReferenceOrForLink
     */
    $ref: string;
    /**
     * A description which by default SHOULD override that of the referenced component. CommonMark syntax MAY be used for rich text representation. If the referenced object-type does not allow a `description` field, then this field has no effect.
     * @type {string}
     * @memberof ReferenceOrForLink
     */
    description?: string | null;
    /**
     * A short summary which by default SHOULD override that of the referenced component. If the referenced object-type does not allow a `summary` field, then this field has no effect.
     * @type {string}
     * @memberof ReferenceOrForLink
     */
    summary?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReferenceOrForLink
     */
    operationRef: string;
    /**
     * 
     * @type {string}
     * @memberof ReferenceOrForLink
     */
    operationId: string;
}


