// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';
import { Operation } from './operation';
import { PathItem } from './path-item';
import { ReferenceOrForExampleAnyOf } from './reference-or-for-example-any-of';
import { ReferenceOrForParameter } from './reference-or-for-parameter';
import { Server } from './server';

/**
 * 
 * @export
 * @interface ReferenceOrForPathItem
 */
export interface ReferenceOrForPathItem {
    /**
     * Allows for a referenced definition of this path item. The referenced structure MUST be in the form of a Path Item Object.  In case a Path Item Object field appears both in the defined object and the referenced object, the behavior is undefined. See the rules for resolving Relative References.
     * @type {string}
     * @memberof ReferenceOrForPathItem
     */
    $ref: string | null;
    /**
     * An optional, string description, intended to apply to all operations in this path. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof ReferenceOrForPathItem
     */
    description?: string | null;
    /**
     * An optional, string summary, intended to apply to all operations in this path.
     * @type {string}
     * @memberof ReferenceOrForPathItem
     */
    summary?: string | null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof ReferenceOrForPathItem
     */
    _delete?: Operation | Null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof ReferenceOrForPathItem
     */
    get?: Operation | Null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof ReferenceOrForPathItem
     */
    head?: Operation | Null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof ReferenceOrForPathItem
     */
    options?: Operation | Null;
    /**
     * A list of parameters that are applicable for all the operations described under this path. These parameters can be overridden at the operation level, but cannot be removed there. The list MUST NOT include duplicated parameters. A unique parameter is defined by a combination of a name and location. The list can use the Reference Object to link to parameters that are defined at the OpenAPI Object\'s components/parameters.
     * @type {Array<ReferenceOrForParameter>}
     * @memberof ReferenceOrForPathItem
     */
    parameters?: Array<ReferenceOrForParameter>;
    /**
     * 
     * @type {Operation | Null}
     * @memberof ReferenceOrForPathItem
     */
    patch?: Operation | Null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof ReferenceOrForPathItem
     */
    post?: Operation | Null;
    /**
     * 
     * @type {Operation | Null}
     * @memberof ReferenceOrForPathItem
     */
    put?: Operation | Null;
    /**
     * An alternative server array to service all operations in this path.
     * @type {Array<Server>}
     * @memberof ReferenceOrForPathItem
     */
    servers?: Array<Server>;
    /**
     * 
     * @type {Operation | Null}
     * @memberof ReferenceOrForPathItem
     */
    trace?: Operation | Null;
}


