// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiKeyLocation } from './api-key-location';
import { OAuth2Flows } from './oauth2-flows';
import { ReferenceOrForExampleAnyOf } from './reference-or-for-example-any-of';
import { SecurityScheme } from './security-scheme';

/**
 * 
 * @export
 * @interface ReferenceOrForSecurityScheme
 */
export interface ReferenceOrForSecurityScheme {
    /**
     * REQUIRED. The reference identifier. This MUST be in the form of a URI.
     * @type {string}
     * @memberof ReferenceOrForSecurityScheme
     */
    $ref: string;
    /**
     * 
     * @type {string}
     * @memberof ReferenceOrForSecurityScheme
     */
    description?: string | null;
    /**
     * A short summary which by default SHOULD override that of the referenced component. If the referenced object-type does not allow a `summary` field, then this field has no effect.
     * @type {string}
     * @memberof ReferenceOrForSecurityScheme
     */
    summary?: string | null;
    /**
     * 
     * @type {ApiKeyLocation}
     * @memberof ReferenceOrForSecurityScheme
     */
    _in: ApiKeyLocation;
    /**
     * 
     * @type {string}
     * @memberof ReferenceOrForSecurityScheme
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof ReferenceOrForSecurityScheme
     */
    type: ReferenceOrForSecuritySchemeTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ReferenceOrForSecurityScheme
     */
    bearerFormat?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReferenceOrForSecurityScheme
     */
    scheme: string;
    /**
     * 
     * @type {OAuth2Flows}
     * @memberof ReferenceOrForSecurityScheme
     */
    flows: OAuth2Flows;
    /**
     * 
     * @type {string}
     * @memberof ReferenceOrForSecurityScheme
     */
    openIdConnectUrl: string;
}

/**
    * @export
    * @enum {string}
    */
export enum ReferenceOrForSecuritySchemeTypeEnum {
    MutualTLS = 'mutualTLS'
}



