// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MediaType } from './media-type';
import { ReferenceOrForExampleAnyOf } from './reference-or-for-example-any-of';
import { RequestBody } from './request-body';

/**
 * 
 * @export
 * @interface ReferenceOrForRequestBody
 */
export interface ReferenceOrForRequestBody {
    /**
     * REQUIRED. The reference identifier. This MUST be in the form of a URI.
     * @type {string}
     * @memberof ReferenceOrForRequestBody
     */
    $ref: string;
    /**
     * A brief description of the request body. This could contain examples of use. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof ReferenceOrForRequestBody
     */
    description?: string | null;
    /**
     * A short summary which by default SHOULD override that of the referenced component. If the referenced object-type does not allow a `summary` field, then this field has no effect.
     * @type {string}
     * @memberof ReferenceOrForRequestBody
     */
    summary?: string | null;
    /**
     * REQUIRED. The content of the request body. The key is a media type or media type range and the value describes it. For requests that match multiple keys, only the most specific key is applicable. e.g. text/plain overrides text/_*
     * @type {{ [key: string]: MediaType; }}
     * @memberof ReferenceOrForRequestBody
     */
    content?: { [key: string]: MediaType; };
    /**
     * Determines if the request body is required in the request. Defaults to false.
     * @type {boolean}
     * @memberof ReferenceOrForRequestBody
     */
    required?: boolean;
}


