// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Example } from './example';
import { ReferenceOrForExampleAnyOf } from './reference-or-for-example-any-of';

/**
 * 
 * @export
 * @interface ReferenceOrForExample
 */
export interface ReferenceOrForExample {
    /**
     * REQUIRED. The reference identifier. This MUST be in the form of a URI.
     * @type {string}
     * @memberof ReferenceOrForExample
     */
    $ref: string;
    /**
     * Long description for the example. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof ReferenceOrForExample
     */
    description?: string | null;
    /**
     * Short description for the example.
     * @type {string}
     * @memberof ReferenceOrForExample
     */
    summary?: string | null;
    /**
     * A URI that points to the literal example. This provides the capability to reference examples that cannot easily be included in JSON or YAML documents. The `value` field and `externalValue` field are mutually exclusive. See the rules for resolving Relative References.
     * @type {string}
     * @memberof ReferenceOrForExample
     */
    externalValue?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ReferenceOrForExample
     */
    value?: string;
}


