// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MediaType } from './media-type';

/**
 * 
 * @export
 * @interface RequestBody
 */
export interface RequestBody {
    [key: string]: object | any;

    /**
     * REQUIRED. The content of the request body. The key is a media type or media type range and the value describes it. For requests that match multiple keys, only the most specific key is applicable. e.g. text/plain overrides text/_*
     * @type {{ [key: string]: MediaType; }}
     * @memberof RequestBody
     */
    content?: { [key: string]: MediaType; };
    /**
     * A brief description of the request body. This could contain examples of use. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof RequestBody
     */
    description?: string | null;
    /**
     * Determines if the request body is required in the request. Defaults to false.
     * @type {boolean}
     * @memberof RequestBody
     */
    required?: boolean;
}


