// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';
import { ReferenceOrForResponse } from './reference-or-for-response';

/**
 * 
 * @export
 * @interface Responses
 */
export interface Responses {
    [key: string]: object | any;

    /**
     * The documentation of responses other than the ones declared for specific HTTP response codes. Use this field to cover undeclared responses.
     * @type {ReferenceOrForResponse | Null}
     * @memberof Responses
     */
    _default?: ReferenceOrForResponse | Null;
}


