// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';
import { SchemaObject2 } from './schema-object2';
import { SingleOrVecForInstanceType } from './single-or-vec-for-instance-type';
import { SingleOrVecForSchema } from './single-or-vec-for-schema';

/**
 * A JSON Schema.
 * @export
 * @interface Schema
 */
export interface Schema {
}


