// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';
import { Schema } from './schema';
import { SingleOrVecForInstanceType } from './single-or-vec-for-instance-type';
import { SingleOrVecForSchema } from './single-or-vec-for-schema';

/**
 * A JSON Schema object.
 * @export
 * @interface SchemaObject2
 */
export interface SchemaObject2 {
    [key: string]: object | any;

    /**
     * The `$id` keyword.  See [JSON Schema 8.2.2. The \"$id\" Keyword](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-8.2.2).
     * @type {string}
     * @memberof SchemaObject2
     */
    $id?: string | null;
    /**
     * The `$ref` keyword.  See [JSON Schema 8.2.4.1. Direct References with \"$ref\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-8.2.4.1).
     * @type {string}
     * @memberof SchemaObject2
     */
    $ref?: string | null;
    /**
     * The `additionalItems` keyword.  See [JSON Schema 9.3.1.2. \"additionalItems\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.3.1.2).
     * @type {Schema | Null}
     * @memberof SchemaObject2
     */
    additionalItems?: Schema | Null;
    /**
     * The `additionalProperties` keyword.  See [JSON Schema 9.3.2.3. \"additionalProperties\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.3.2.3).
     * @type {Schema | Null}
     * @memberof SchemaObject2
     */
    additionalProperties?: Schema | Null;
    /**
     * The `allOf` keyword.  See [JSON Schema 9.2.1.1. \"allOf\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.2.1.1).
     * @type {Array<Schema>}
     * @memberof SchemaObject2
     */
    allOf?: Array<Schema> | null;
    /**
     * The `anyOf` keyword.  See [JSON Schema 9.2.1.2. \"anyOf\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.2.1.2).
     * @type {Array<Schema>}
     * @memberof SchemaObject2
     */
    anyOf?: Array<Schema> | null;
    /**
     * 
     * @type {string}
     * @memberof SchemaObject2
     */
    _const?: string;
    /**
     * The `contains` keyword.  See [JSON Schema 9.3.1.4. \"contains\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.3.1.4).
     * @type {Schema | Null}
     * @memberof SchemaObject2
     */
    contains?: Schema | Null;
    /**
     * 
     * @type {string}
     * @memberof SchemaObject2
     */
    _default?: string;
    /**
     * The `deprecated` keyword.  See [JSON Schema Validation 9.3. \"deprecated\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-9.3).
     * @type {boolean}
     * @memberof SchemaObject2
     */
    deprecated?: boolean;
    /**
     * The `description` keyword.  See [JSON Schema Validation 9.1. \"title\" and \"description\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-9.1).
     * @type {string}
     * @memberof SchemaObject2
     */
    description?: string | null;
    /**
     * The `else` keyword.  See [JSON Schema 9.2.2.3. \"else\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.2.2.3).
     * @type {Schema | Null}
     * @memberof SchemaObject2
     */
    _else?: Schema | Null;
    /**
     * The `enum` keyword.  See [JSON Schema Validation 6.1.2. \"enum\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.1.2)
     * @type {Array<object>}
     * @memberof SchemaObject2
     */
    _enum?: Array<object> | null;
    /**
     * The `examples` keyword.  See [JSON Schema Validation 9.5. \"examples\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-9.5).
     * @type {Array<object>}
     * @memberof SchemaObject2
     */
    examples?: Array<object>;
    /**
     * The `exclusiveMaximum` keyword.  See [JSON Schema Validation 6.2.3. \"exclusiveMaximum\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.2.3).
     * @type {number}
     * @memberof SchemaObject2
     */
    exclusiveMaximum?: number | null;
    /**
     * The `exclusiveMinimum` keyword.  See [JSON Schema Validation 6.2.5. \"exclusiveMinimum\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.2.5).
     * @type {number}
     * @memberof SchemaObject2
     */
    exclusiveMinimum?: number | null;
    /**
     * The `format` keyword.  See [JSON Schema Validation 7. A Vocabulary for Semantic Content With \"format\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-7).
     * @type {string}
     * @memberof SchemaObject2
     */
    format?: string | null;
    /**
     * The `if` keyword.  See [JSON Schema 9.2.2.1. \"if\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.2.2.1).
     * @type {Schema | Null}
     * @memberof SchemaObject2
     */
    _if?: Schema | Null;
    /**
     * The `items` keyword.  See [JSON Schema 9.3.1.1. \"items\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.3.1.1).
     * @type {SingleOrVecForSchema | Null}
     * @memberof SchemaObject2
     */
    items?: SingleOrVecForSchema | Null;
    /**
     * The `maxItems` keyword.  See [JSON Schema Validation 6.4.1. \"maxItems\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.4.1).
     * @type {number}
     * @memberof SchemaObject2
     */
    maxItems?: number | null;
    /**
     * The `maxLength` keyword.  See [JSON Schema Validation 6.3.1. \"maxLength\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.3.1).
     * @type {number}
     * @memberof SchemaObject2
     */
    maxLength?: number | null;
    /**
     * The `maxProperties` keyword.  See [JSON Schema Validation 6.5.1. \"maxProperties\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.5.1).
     * @type {number}
     * @memberof SchemaObject2
     */
    maxProperties?: number | null;
    /**
     * The `maximum` keyword.  See [JSON Schema Validation 6.2.2. \"maximum\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.2.2).
     * @type {number}
     * @memberof SchemaObject2
     */
    maximum?: number | null;
    /**
     * The `minItems` keyword.  See [JSON Schema Validation 6.4.2. \"minItems\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.4.2).
     * @type {number}
     * @memberof SchemaObject2
     */
    minItems?: number | null;
    /**
     * The `minLength` keyword.  See [JSON Schema Validation 6.3.2. \"minLength\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.3.2).
     * @type {number}
     * @memberof SchemaObject2
     */
    minLength?: number | null;
    /**
     * The `minProperties` keyword.  See [JSON Schema Validation 6.5.2. \"minProperties\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.5.2).
     * @type {number}
     * @memberof SchemaObject2
     */
    minProperties?: number | null;
    /**
     * The `minimum` keyword.  See [JSON Schema Validation 6.2.4. \"minimum\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.2.4).
     * @type {number}
     * @memberof SchemaObject2
     */
    minimum?: number | null;
    /**
     * The `multipleOf` keyword.  See [JSON Schema Validation 6.2.1. \"multipleOf\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.2.1).
     * @type {number}
     * @memberof SchemaObject2
     */
    multipleOf?: number | null;
    /**
     * The `not` keyword.  See [JSON Schema 9.2.1.4. \"not\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.2.1.4).
     * @type {Schema | Null}
     * @memberof SchemaObject2
     */
    not?: Schema | Null;
    /**
     * The `oneOf` keyword.  See [JSON Schema 9.2.1.3. \"oneOf\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.2.1.3).
     * @type {Array<Schema>}
     * @memberof SchemaObject2
     */
    oneOf?: Array<Schema> | null;
    /**
     * The `pattern` keyword.  See [JSON Schema Validation 6.3.3. \"pattern\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.3.3).
     * @type {string}
     * @memberof SchemaObject2
     */
    pattern?: string | null;
    /**
     * The `patternProperties` keyword.  See [JSON Schema 9.3.2.2. \"patternProperties\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.3.2.2).
     * @type {{ [key: string]: Schema; }}
     * @memberof SchemaObject2
     */
    patternProperties?: { [key: string]: Schema; };
    /**
     * The `properties` keyword.  See [JSON Schema 9.3.2.1. \"properties\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.3.2.1).
     * @type {{ [key: string]: Schema; }}
     * @memberof SchemaObject2
     */
    properties?: { [key: string]: Schema; };
    /**
     * The `propertyNames` keyword.  See [JSON Schema 9.3.2.5. \"propertyNames\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.3.2.5).
     * @type {Schema | Null}
     * @memberof SchemaObject2
     */
    propertyNames?: Schema | Null;
    /**
     * The `readOnly` keyword.  See [JSON Schema Validation 9.4. \"readOnly\" and \"writeOnly\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-9.4).
     * @type {boolean}
     * @memberof SchemaObject2
     */
    readOnly?: boolean;
    /**
     * The `required` keyword.  See [JSON Schema Validation 6.5.3. \"required\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.5.3).
     * @type {Array<string>}
     * @memberof SchemaObject2
     */
    required?: Array<string>;
    /**
     * The `then` keyword.  See [JSON Schema 9.2.2.2. \"then\"](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-9.2.2.2).
     * @type {Schema | Null}
     * @memberof SchemaObject2
     */
    then?: Schema | Null;
    /**
     * The `title` keyword.  See [JSON Schema Validation 9.1. \"title\" and \"description\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-9.1).
     * @type {string}
     * @memberof SchemaObject2
     */
    title?: string | null;
    /**
     * The `type` keyword.  See [JSON Schema Validation 6.1.1. \"type\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.1.1) and [JSON Schema 4.2.1. Instance Data Model](https://tools.ietf.org/html/draft-handrews-json-schema-02#section-4.2.1).
     * @type {SingleOrVecForInstanceType | Null}
     * @memberof SchemaObject2
     */
    type?: SingleOrVecForInstanceType | Null;
    /**
     * The `uniqueItems` keyword.  See [JSON Schema Validation 6.4.3. \"uniqueItems\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-6.4.3).
     * @type {boolean}
     * @memberof SchemaObject2
     */
    uniqueItems?: boolean | null;
    /**
     * The `writeOnly` keyword.  See [JSON Schema Validation 9.4. \"readOnly\" and \"writeOnly\"](https://tools.ietf.org/html/draft-handrews-json-schema-validation-02#section-9.4).
     * @type {boolean}
     * @memberof SchemaObject2
     */
    writeOnly?: boolean;
}


