// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SecuritySchemeOneOf3
 */
export interface SecuritySchemeOneOf3 {
    /**
     * 
     * @type {string}
     * @memberof SecuritySchemeOneOf3
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SecuritySchemeOneOf3
     */
    openIdConnectUrl: string;
    /**
     * 
     * @type {string}
     * @memberof SecuritySchemeOneOf3
     */
    type: SecuritySchemeOneOf3TypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SecuritySchemeOneOf3TypeEnum {
    OpenIdConnect = 'openIdConnect'
}



