// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiKeyLocation } from './api-key-location';
import { OAuth2Flows } from './oauth2-flows';
import { SecuritySchemeOneOf } from './security-scheme-one-of';
import { SecuritySchemeOneOf1 } from './security-scheme-one-of1';
import { SecuritySchemeOneOf2 } from './security-scheme-one-of2';
import { SecuritySchemeOneOf3 } from './security-scheme-one-of3';
import { SecuritySchemeOneOf4 } from './security-scheme-one-of4';

/**
 * @type SecurityScheme
 * Defines a security scheme that can be used by the operations. Supported schemes are HTTP authentication, an API key (either as a header or as a query parameter), OAuth2\'s common flows (implicit, password, application and access code) as defined in RFC6749, and OpenID Connect Discovery.
 * @export
 */
export type SecurityScheme = SecuritySchemeOneOf | SecuritySchemeOneOf1 | SecuritySchemeOneOf2 | SecuritySchemeOneOf3 | SecuritySchemeOneOf4;



