// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ApiKeyLocation } from './api-key-location';

/**
 * 
 * @export
 * @interface SecuritySchemeOneOf
 */
export interface SecuritySchemeOneOf {
    /**
     * 
     * @type {string}
     * @memberof SecuritySchemeOneOf
     */
    description?: string | null;
    /**
     * 
     * @type {ApiKeyLocation}
     * @memberof SecuritySchemeOneOf
     */
    _in: ApiKeyLocation;
    /**
     * 
     * @type {string}
     * @memberof SecuritySchemeOneOf
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SecuritySchemeOneOf
     */
    type: SecuritySchemeOneOfTypeEnum;
}

/**
    * @export
    * @enum {string}
    */
export enum SecuritySchemeOneOfTypeEnum {
    ApiKey = 'apiKey'
}



