// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ServerVariable } from './server-variable';

/**
 * An object representing a Server.
 * @export
 * @interface Server
 */
export interface Server {
    [key: string]: object | any;

    /**
     * An optional string describing the host designated by the URL. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof Server
     */
    description?: string | null;
    /**
     * REQUIRED. A URL to the target host. This URL supports Server Variables and MAY be relative, to indicate that the host location is relative to the location where the OpenAPI document is being served. Variable substitutions will be made when a variable is named in {brackets}.
     * @type {string}
     * @memberof Server
     */
    url: string;
    /**
     * A map between a variable name and its value. The value is used for substitution in the server\'s URL template.
     * @type {{ [key: string]: ServerVariable; }}
     * @memberof Server
     */
    variables?: { [key: string]: ServerVariable; };
}


