// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { Null } from './null';
import { Schema } from './schema';
import { SingleOrVecForInstanceType } from './single-or-vec-for-instance-type';
import { SingleOrVecForSchema } from './single-or-vec-for-schema';

/**
 * A type which can be serialized as a single item, or multiple items.  In some contexts, a `Single` may be semantically distinct from a `Vec` containing only item.
 * @export
 * @interface SingleOrVecForSchema
 */
export interface SingleOrVecForSchema {
}


