// tslint:disable
/**
 * Skadi Documention Generator
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { InstanceType } from './instance-type';

/**
 * A type which can be serialized as a single item, or multiple items.  In some contexts, a `Single` may be semantically distinct from a `Vec` containing only item.
 * @export
 * @interface SingleOrVecForInstanceType
 */
export interface SingleOrVecForInstanceType {
}


