// tslint:disable
/**
 * 调位置
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { ExternalDocumentation } from './external-documentation';
import { Null } from './null';

/**
 * Adds metadata to a single tag that is used by the Operation Object. It is not mandatory to have a Tag Object per tag defined in the Operation Object instances.
 * @export
 * @interface Tag
 */
export interface Tag {
    [key: string]: object | any;

    /**
     * A description for the tag. CommonMark syntax MAY be used for rich text representation.
     * @type {string}
     * @memberof Tag
     */
    description?: string | null;
    /**
     * Additional external documentation for this tag.
     * @type {ExternalDocumentation | Null}
     * @memberof Tag
     */
    externalDocs?: ExternalDocumentation | Null;
    /**
     * REQUIRED. The name of the tag.
     * @type {string}
     * @memberof Tag
     */
    name: string;
}


